// Code generated by errcdgen; DO NOT EDIT.
package example

import (
	"errors"
	"gitlab.com/errcdgen"
)

// InvalidInputParameterErr format "is invalid input parameter: %v"
// - Level: error
// - exitCode: 1
func NewInvalidInputParameterErr(err error, payload map[string]interface{}) *errcdgen.CodeError {
	return InvalidInputParameterErr.WithArgs(payload).WithError(err)
}

// 同時に作成される
func IsInvalidInputParameterErr(err error) bool {
	var cerr *errcdgen.CodeError
	if as := errors.As(err, &cerr); as {
		if cerr.Code == InvalidInputParameterErr.Code {
			return true
		}
	}
	return false
}

func NewNotFoundOperationIDErr(err error) *errcdgen.CodeError {
	return NotFoundOperationIDErr.WithError(err)
}

// 指定がないと型が未定義
func NewUpdateConflictErr(err error, arg1 interface{}) *errcdgen.CodeError {
	return UpdateConflictErr.WithArgs(arg1)
}

// errの引数付きで作成
func NewUserTypeUnregisterErr() *errcdgen.CodeError {
	return UserTypeUnregisterErr
}
