image: golang:1.14

variables:
  REPO_NAME: gitlab.com/osaki-lab/reguerr

stages:
  - build
  - test

before_script:
  - mkdir -p /go/src/gitlab.com/osaki-lab/
  - cp -fr ../reguerr /go/src/gitlab.com/osaki-lab/
  - /go/src/gitlab.com/osaki-lab/reguerr/

build:
  stage: build
  script:
    - go build

test:
  stage: test
  script:
    - go test
  dependencies:
    - build
