// Code generated by "stringer -type=Level"; DO NOT EDIT.

package reguerr

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Trace-1]
	_ = x[Debug-2]
	_ = x[Info-3]
	_ = x[Warn-4]
	_ = x[Error-5]
	_ = x[Fatal-6]
	_ = x[Unknown-7]
}

const _Level_name = "TraceDebugInfoWarnErrorFatalUnknown"

var _Level_index = [...]uint8{0, 5, 10, 14, 18, 23, 28, 35}

func (i Level) String() string {
	i -= 1
	if i < 0 || i >= Level(len(_Level_index)-1) {
		return "Level(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Level_name[_Level_index[i]:_Level_index[i+1]]
}
